# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - travis_wait R CMD check *tar.gz
